
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J20} [get_ports lcd_clk]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E17} [get_ports {lcd_ctrl[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN B20} [get_ports {lcd_ctrl[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN C20} [get_ports {lcd_ctrl[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D18} [get_ports {lcd_ctrl[0]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H20} [get_ports lcd_hsync]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H15} [get_ports lcd_vsync]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E18} [get_ports {lcd_B[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E19} [get_ports {lcd_B[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L19} [get_ports {lcd_B[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L20} [get_ports {lcd_B[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M17} [get_ports {lcd_B[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M18} [get_ports {lcd_B[0]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L16} [get_ports {lcd_G[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L17} [get_ports {lcd_G[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H16} [get_ports {lcd_G[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H17} [get_ports {lcd_G[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G17} [get_ports {lcd_G[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G18} [get_ports {lcd_G[0]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G19} [get_ports {lcd_R[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G20} [get_ports {lcd_R[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K14} [get_ports {lcd_R[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J14} [get_ports {lcd_R[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N15} [get_ports {lcd_R[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G15} [get_ports {lcd_R[0]}]


